AxonFramework/axon-bom

.github/dependabot.yml
.github/release-notes.yml
.github/workflows/release-notes.yml

Just updating dependabot to check for action versions and release-notes workflow to latest

Updated actions and dependabot

---

pom.xml

Added project reactor version in order to avoid issues when upgrading from an older Axon version.
This resolves issue https://github.com/AxonFramework/axon-bom/issues/11

Added project reactor version

---

pom.xml

This pull request updates Axon Framework to version 4.5.9.

Update Axon Framework to 4.5.9

---

README.md

To make it clear to the users of the Bill of Materials, the README should include when the BoM is updated.

Update README.md with release cycle

---

pom.xml

Upgrade Axon Framework from 4.5.11 to 4.5.12

Upgrade Axon Framework from 4.5.11 to 4.5.12

---

pom.xml

We have a new module in Axon Framework. I've added it to the BoM.

Add axon-tracing-opentelemetry to the BoM

---

README.md
pom.xml

This pull request adds the new [Axon Framework Multi-Tenancy](https://github.com/AxonFramework/extension-multitenancy) and experimental [Axon Framework Spring Native](https://github.com/AxonFramework/extension-spring-native) dependencies.

Add the new multi-tenancy and Spring Native extensions

---

pom.xml

This pull requests adds Axon Framework's new Jakarta modules.
More specifically, it adds:
- `axon-configuration-jakarta`
- `axon-eventsourcing-jakarta`
- `axon-messaging-jakarta`
- `axon-modelling-jakarta`

Add Axon Framework's Jakarta modules

---

pom.xml

Upgrade from Multitenancy extension version 4.6.0 to 4.6.2

Upgrade from Multitenancy extension version 4.6.0 to 4.6.2

---

pom.xml

This pull request upgrades Axon Framework from 4.6.2 to 4.6.3.

Upgrade Axon Framework to 4.6.3

---

README.md
pom.xml

It can only be rightfully merged after the JobRunr extension has been released.

Add JobRunrPro extension.

---

pom.xml

Upgrade Axon Server Connector Java to 2023.1.0

Upgrade Axon Server Connector Java to 2023.1.0

---

pom.xml

This pull request upgrades the following dependencies:
- Axon Framework to 4.8.1
- Axon Framework's Reactor Extension to 4.8.1

Upgrade Axon Framework and Reactor Extension to 4.8.1

---

pom.xml

Update Axon Framework to 4.8.3

Update Axon Framework to 4.8.3

---

pom.xml

This pull request upgrades the Axon Server Connector Java dependency to 2023.1.1.

Upgrade Axon Server Connector Java to 2023.1.1

---

pom.xml

This pull request upgrades Axon Framework from 4.9.0 to 4.9.1.

Upgrade Axon Framework to 4.9.1

---

pom.xml

This pull request updates the Axon Framework version to 4.9.2, and the Axon Framework Spring AOT Extension version to 4.9.1.

Upgrade to Axon Framework 4.9.2 and Axon Framework Spring AOT 4.9.1

---

pom.xml

Upgrade Axon Framework to 4.10.0
Upgrade all Axon Framework extensions to 4.10.0
Upgrade Axon Server Connector Java to 2024.1.0
Upgrade Axon Server Plugin API to 4.8.1

Upgrade all Axon-related dependencies

---

pom.xml

This pull request updates the Axon Framework version from [4.10.0](https://github.com/AxonFramework/AxonFramework/releases/tag/axon-4.10.0)  to [4.10.1](https://github.com/AxonFramework/AxonFramework/releases/tag/axon-4.10.1).

Update Axon Framework to 4.10.1

---

pom.xml

Upgrade Axon Framework to 4.11.1

Upgrade Axon Framework to 4.11.1

---

pom.xml

This pull request updates the following dependencies:
- Axon Framework to 4.11.2
- Kafka Extension to 4.11.1
- Mongo Extension to 4.11.1

Update Axon Framework, Kafka Extension, and Mongo Extension

---

pom.xml

This pull request upgrades the Kotlin Extension from 4.11.0 to 4.11.1.

Upgrade Kotlin Extension to 4.11.1
